language: ruby

before_script:
- psql -U postgres -c "create user rails_kvartplata with password 'rails_kvartplata' SUPERUSER;"
- psql -U postgres -c "create database kvartplata_development;"
- bundle exec rake db:migrate

script: bundle exec rake spec