
development:
  adapter:  postgresql
  encoding: unicode
  reconnect: false
  database: kvartplata_development
  pool: 5
  username:
  password:
  host: localhost
  timeout: 5000


test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: kvartplata_test
  pool: 5
  username:
  password:
  host: localhost
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: kvartplata_production
  pool: 5
  username:
  password:
  host: localhost
  timeout: 5000
