
development:
  adapter:  postgresql
  encoding: unicode
  reconnect: false
  database: kvartplata_development
  pool: 5
  username: rails_kvartplata
  password: rails_kvartplata
  host: localhost
  timeout: 5000


test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: kvartplata_test
  pool: 5
  username: rails_kvartplata
  password: rails_kvartplata
  host: localhost
  timeout: 5000
